# Makefile.am: development automation sources

EXTRA_fuse_SOURCES += \
	     automation/automation.c \
	     automation/automation.h \
	     automation/json.c \
	     automation/json.h

if ENABLE_AUTOMATION
fuse_SOURCES += \
	automation/automation.c \
	automation/automation.h \
	automation/json.c \
	automation/json.h
endif
